#include <iostream>
#include "print_info.h"

void printUsage()
{
std::cout << " 1 RIL_REQUEST_GET_SIM_STATUS" << std::endl;
std::cout << " 2 RIL_REQUEST_ENTER_SIM_PIN" << std::endl;
std::cout << " 3 RIL_REQUEST_ENTER_SIM_PUK" << std::endl;
std::cout << " 4 RIL_REQUEST_ENTER_SIM_PIN2" << std::endl;
std::cout << " 5 RIL_REQUEST_ENTER_SIM_PUK2" << std::endl;
std::cout << " 6 RIL_REQUEST_CHANGE_SIM_PIN" << std::endl;
std::cout << " 7 RIL_REQUEST_CHANGE_SIM_PIN2" << std::endl;
std::cout << " 8 RIL_REQUEST_ENTER_NETWORK_DEPERSONALIZATION" << std::endl;
std::cout << " 9 RIL_REQUEST_GET_CURRENT_CALLS" << std::endl;
std::cout << "10 RIL_REQUEST_DIAL" << std::endl;
std::cout << "11 RIL_REQUEST_GET_IMSI" << std::endl;
std::cout << "12 RIL_REQUEST_HANGUP" << std::endl;
std::cout << "13 RIL_REQUEST_HANGUP_WAITING_OR_BACKGROUND" << std::endl;
std::cout << "14 RIL_REQUEST_HANGUP_FOREGROUND_RESUME_BACKGROUND" << std::endl;
std::cout << "15 RIL_REQUEST_SWITCH_WAITING_OR_HOLDING_AND_ACTIVE" << std::endl;
std::cout << "16 RIL_REQUEST_CONFERENCE" << std::endl;
std::cout << "17 RIL_REQUEST_UDUB" << std::endl;
std::cout << "18 RIL_REQUEST_LAST_CALL_FAIL_CAUSE" << std::endl;
std::cout << "19 RIL_REQUEST_SIGNAL_STRENGTH" << std::endl;
std::cout << "20 RIL_REQUEST_VOICE_REGISTRATION_STATE" << std::endl;
std::cout << "21 RIL_REQUEST_DATA_REGISTRATION_STATE" << std::endl;
std::cout << "22 RIL_REQUEST_OPERATOR" << std::endl;
std::cout << "23 RIL_REQUEST_RADIO_POWER" << std::endl;
std::cout << "24 RIL_REQUEST_DTMF" << std::endl;
std::cout << "25 RIL_REQUEST_SEND_SMS" << std::endl;
std::cout << "26 RIL_REQUEST_SEND_SMS_EXPECT_MORE" << std::endl;
std::cout << "27 RIL_REQUEST_SETUP_DATA_CALL" << std::endl;
std::cout << "28 RIL_REQUEST_SIM_IO" << std::endl;
std::cout << "29 RIL_REQUEST_SEND_USSD" << std::endl;
std::cout << "30 RIL_REQUEST_CANCEL_USSD" << std::endl;
std::cout << "31 RIL_REQUEST_GET_CLIR" << std::endl;
std::cout << "32 RIL_REQUEST_SET_CLIR" << std::endl;
std::cout << "33 RIL_REQUEST_QUERY_CALL_FORWARD_STATUS" << std::endl;
std::cout << "34 RIL_REQUEST_SET_CALL_FORWARD" << std::endl;
std::cout << "35 RIL_REQUEST_QUERY_CALL_WAITING" << std::endl;
std::cout << "36 RIL_REQUEST_SET_CALL_WAITING" << std::endl;
std::cout << "37 RIL_REQUEST_SMS_ACKNOWLEDGE" << std::endl;
std::cout << "38 RIL_REQUEST_GET_IMEI" << std::endl;
std::cout << "39 RIL_REQUEST_GET_IMEISV" << std::endl;
std::cout << "40 RIL_REQUEST_ANSWER" << std::endl;
std::cout << "41 RIL_REQUEST_DEACTIVATE_DATA_CALL" << std::endl;
std::cout << "42 RIL_REQUEST_QUERY_FACILITY_LOCK" << std::endl;
std::cout << "43 RIL_REQUEST_SET_FACILITY_LOCK" << std::endl;
std::cout << "44 RIL_REQUEST_CHANGE_BARRING_PASSWORD" << std::endl;
std::cout << "45 RIL_REQUEST_QUERY_NETWORK_SELECTION_MODE" << std::endl;
std::cout << "46 RIL_REQUEST_SET_NETWORK_SELECTION_AUTOMATIC" << std::endl;
std::cout << "47 RIL_REQUEST_SET_NETWORK_SELECTION_MANUAL" << std::endl;
std::cout << "48 RIL_REQUEST_QUERY_AVAILABLE_NETWORKS" << std::endl;
std::cout << "49 RIL_REQUEST_DTMF_START" << std::endl;
std::cout << "50 RIL_REQUEST_DTMF_STOP" << std::endl;
std::cout << "51 RIL_REQUEST_BASEBAND_VERSION" << std::endl;
std::cout << "52 RIL_REQUEST_SEPARATE_CONNECTION" << std::endl;
std::cout << "53 RIL_REQUEST_SET_MUTE" << std::endl;
std::cout << "54 RIL_REQUEST_GET_MUTE" << std::endl;
std::cout << "55 RIL_REQUEST_QUERY_CLIP" << std::endl;
std::cout << "56 RIL_REQUEST_LAST_DATA_CALL_FAIL_CAUSE" << std::endl;
std::cout << "57 RIL_REQUEST_DATA_CALL_LIST" << std::endl;
std::cout << "58 RIL_REQUEST_RESET_RADIO" << std::endl;
std::cout << "59 RIL_REQUEST_OEM_HOOK_RAW" << std::endl;
std::cout << "60 RIL_REQUEST_OEM_HOOK_STRINGS" << std::endl;
std::cout << "61 RIL_REQUEST_SCREEN_STATE" << std::endl;
std::cout << "62 RIL_REQUEST_SET_SUPP_SVC_NOTIFICATION" << std::endl;
std::cout << "63 RIL_REQUEST_WRITE_SMS_TO_SIM" << std::endl;
std::cout << "64 RIL_REQUEST_DELETE_SMS_ON_SIM" << std::endl;
std::cout << "65 RIL_REQUEST_SET_BAND_MODE" << std::endl;
std::cout << "66 RIL_REQUEST_QUERY_AVAILABLE_BAND_MODE" << std::endl;
std::cout << "67 RIL_REQUEST_STK_GET_PROFILEg" << std::endl;
std::cout << "68 RIL_REQUEST_STK_SET_PROFILE" << std::endl;
std::cout << "69 RIL_REQUEST_STK_SEND_ENVELOPE_COMMAND" << std::endl;
std::cout << "70 RIL_REQUEST_STK_SEND_TERMINAL_RESPONSE" << std::endl;
std::cout << "71 RIL_REQUEST_STK_HANDLE_CALL_SETUP_REQUESTED_FROM_SIM" << std::endl;
std::cout << "72 RIL_REQUEST_EXPLICIT_CALL_TRANSFER" << std::endl;
std::cout << "73 RIL_REQUEST_SET_PREFERRED_NETWORK_TYPE" << std::endl;
std::cout << "74 RIL_REQUEST_GET_PREFERRED_NETWORK_TYPE" << std::endl;
std::cout << "75 RIL_REQUEST_GET_NEIGHBORING_CELL_IDS" << std::endl;
std::cout << "76 RIL_REQUEST_SET_LOCATION_UPDATES" << std::endl;
std::cout << "77 RIL_REQUEST_CDMA_SET_SUBSCRIPTION_SOURCE" << std::endl;
std::cout << "78 RIL_REQUEST_CDMA_SET_ROAMING_PREFERENCE" << std::endl;
std::cout << "79 RIL_REQUEST_CDMA_QUERY_ROAMING_PREFERENCE" << std::endl;
std::cout << "80 RIL_REQUEST_SET_TTY_MODE" << std::endl;
std::cout << "81 RIL_REQUEST_QUERY_TTY_MODE" << std::endl;
std::cout << "82 RIL_REQUEST_CDMA_SET_PREFERRED_VOICE_PRIVACY_MODE" << std::endl;
std::cout << "83 RIL_REQUEST_CDMA_QUERY_PREFERRED_VOICE_PRIVACY_MODE" << std::endl;
std::cout << "84 RIL_REQUEST_CDMA_FLASH" << std::endl;
std::cout << "85 RIL_REQUEST_CDMA_BURST_DTMF" << std::endl;
std::cout << "86 RIL_REQUEST_CDMA_VALIDATE_AND_WRITE_AKEY" << std::endl;
std::cout << "87 RIL_REQUEST_CDMA_SEND_SMS" << std::endl;
std::cout << "88 RIL_REQUEST_CDMA_SMS_ACKNOWLEDGE" << std::endl;
std::cout << "89 RIL_REQUEST_GSM_GET_BROADCAST_SMS_CONFIG" << std::endl;
std::cout << "90 RIL_REQUEST_GSM_SET_BROADCAST_SMS_CONFIG" << std::endl;
std::cout << "91 RIL_REQUEST_GSM_SMS_BROADCAST_ACTIVATION" << std::endl;
std::cout << "92 RIL_REQUEST_CDMA_GET_BROADCAST_SMS_CONFIG" << std::endl;
std::cout << "93 RIL_REQUEST_CDMA_SET_BROADCAST_SMS_CONFIG" << std::endl;
std::cout << "94 RIL_REQUEST_CDMA_SMS_BROADCAST_ACTIVATION" << std::endl;
std::cout << "95 RIL_REQUEST_CDMA_SUBSCRIPTION, dispatchVoid" << std::endl;
std::cout << "96 RIL_REQUEST_CDMA_WRITE_SMS_TO_RUIM" << std::endl;
std::cout << "97 RIL_REQUEST_CDMA_DELETE_SMS_ON_RUIM" << std::endl;
std::cout << "98 RIL_REQUEST_DEVICE_IDENTITY" << std::endl;
std::cout << "99 RIL_REQUEST_EXIT_EMERGENCY_CALLBACK_MODE" << std::endl;
std::cout << "100 RIL_REQUEST_GET_SMSC_ADDRESS" << std::endl;
std::cout << "101 RIL_REQUEST_SET_SMSC_ADDRESS" << std::endl;
std::cout << "102 RIL_REQUEST_REPORT_SMS_MEMORY_STATUS" << std::endl;
std::cout << "103 RIL_REQUEST_REPORT_STK_SERVICE_IS_RUNNING" << std::endl;
std::cout << "104 RIL_REQUEST_CDMA_GET_SUBSCRIPTION_SOURCE" << std::endl;
std::cout << "105 RIL_REQUEST_ISIM_AUTHENTICATION" << std::endl;
std::cout << "106 RIL_REQUEST_ACKNOWLEDGE_INCOMING_GSM_SMS_WITH_PDU" << std::endl;
std::cout << "107 RIL_REQUEST_STK_SEND_ENVELOPE_WITH_STATUS" << std::endl;
std::cout << "108 RIL_REQUEST_VOICE_RADIO_TECH" << std::endl;
std::cout << "109 RIL_REQUEST_GET_CELL_INFO_LIST" << std::endl;
std::cout << "110 RIL_REQUEST_SET_UNSOL_CELL_INFO_LIST_RATE" << std::endl;
std::cout << "111 RIL_REQUEST_SET_INITIAL_ATTACH_APN" << std::endl;
std::cout << "112 RIL_REQUEST_IMS_REGISTRATION_STATE" << std::endl;
std::cout << "113 RIL_REQUEST_IMS_SEND_SMS" << std::endl;
std::cout << "114 RIL_REQUEST_SIM_TRANSMIT_APDU_BASIC" << std::endl;
std::cout << "115 RIL_REQUEST_SIM_OPEN_CHANNEL" << std::endl;
std::cout << "116 RIL_REQUEST_SIM_CLOSE_CHANNEL" << std::endl;
std::cout << "117 RIL_REQUEST_SIM_TRANSMIT_APDU_CHANNEL" << std::endl;
std::cout << "118 RIL_REQUEST_NV_READ_ITEM" << std::endl;
std::cout << "119 RIL_REQUEST_NV_WRITE_ITEM" << std::endl;
std::cout << "120 RIL_REQUEST_NV_WRITE_CDMA_PRL" << std::endl;
std::cout << "121 RIL_REQUEST_NV_RESET_CONFIG" << std::endl;
std::cout << "122 RIL_REQUEST_SET_UICC_SUBSCRIPTION" << std::endl;
std::cout << "123 RIL_REQUEST_ALLOW_DATA" << std::endl;
std::cout << "124 RIL_REQUEST_GET_HARDWARE_CONFIG" << std::endl;
std::cout << "125 125 RIL_REQUEST_SIM_AUTHENTICATION" << std::endl;
std::cout << "126 RIL_REQUEST_GET_DC_RT_INFO" << std::endl;
std::cout << "127 RIL_REQUEST_SET_DC_RT_INFO_RATE" << std::endl;
std::cout << "128 RIL_REQUEST_SET_DATA_PROFILE" << std::endl;
std::cout << "129 RIL_REQUEST_SHUTDOWN" << std::endl;
std::cout << "130 RIL_REQUEST_GET_RADIO_CAPABILITY" << std::endl;
std::cout << "131 RIL_REQUEST_SET_RADIO_CAPABILITY" << std::endl;
std::cout << "132 RIL_REQUEST_START_LCE" << std::endl;
std::cout << "133 RIL_REQUEST_STOP_LCE" << std::endl;
std::cout << "134 RIL_REQUEST_PULL_LCEDATA" << std::endl;
std::cout << "135 RIL_REQUEST_GET_ACTIVITY_INFO" << std::endl;
std::cout << "136 RIL_REQUEST_SET_CARRIER_RESTRICTIONS" << std::endl;
std::cout << "137 RIL_REQUEST_GET_CARRIER_RESTRICTIONS" << std::endl;
std::cout << "138 RIL_REQUEST_SIM_GET_ATR" << std::endl;
std::cout << "139 RIL_REQUEST_CAF_SIM_OPEN_CHANNEL_WITH_P2" << std::endl;
std::cout << "140 RIL_REQUEST_GET_ADN_RECORD" << std::endl;
std::cout << "141 RIL_REQUEST_UPDATE_ADN_RECORD" << std::endl;
std::cout << "142 RIL_REQUEST_GET_ECALL_OPRT_MODE" << std::endl;
std::cout << "143 RIL_REQUEST_SET_ECALL_OPRT_MODE" << std::endl;

}

